export const CREATE_ANSWER_ERROR = 'CREATE_ANSWER_ERROR';
export const CREATE_ANSWER_SUCCESS = 'CREATE_ANSWER_SUCCESS';

export const CREATE_ANSWER_ANSWER = 'CREATE_ANSWER_ANSWER';
export const CREATE_ANSWER_ANSWER_ERROR = 'CREATE_ANSWER_ANSWER_ERROR';
export const CREATE_ANSWER_ANSWER_SUCCESS = 'CREATE_ANSWER_ANSWER_SUCCESS';

export const DELETE_ANSWER_ERROR = 'DELETE_ANSWER_ERROR';
export const DELETE_ANSWER_SUCCESS = 'DELETE_ANSWER_SUCCESS';

export const UNDELETE_ANSWER_ERROR = 'UNDELETE_ANSWER_ERROR';

export const UPDATE_ANSWER_ERROR = 'UPDATE_ANSWER_ERROR';
export const UPDATE_ANSWER_SUCCESS = 'UPDATE_ANSWER_SUCCESS';

export const FILTER_ANSWERS = 'FILTER_ANSWERS';
export const FILTER_ANSWER_SELECTED = 'FILTER_ANSWER_SELECTED';
export const LOAD_ANSWERS_SUCCESS = 'LOAD_ANSWERS_SUCCESS';
export const UNLOAD_ANSWERS_SUCCESS = 'UNLOAD_ANSWERS_SUCCESS';

export const FETCH_APPRANK_SUCCESS = 'FETCH_APPRANK_SUCCESS';