export const GET_MOST_RECOMMENDED_APP_ICON_SUCCESS = 'GET_MOST_RECOMMENDED_APP_ICON_SUCCESS';
export const FETCH_ISSUE_SUCCESS = 'FETCH_ISSUE_SUCCESS';
export const FETCH_ISSUE_APP_RANK_SUCCESS = 'FETCH_ISSUE_APP_RANK_SUCCESS';
export const UNLOAD_ISSUE_SUCCESS = 'UNLOAD_ISSUE_SUCCESS';
export const FETCH_LIKES_QUESTION_SUCCESS = 'FETCH_LIKES_QUESTION_SUCCESS';
export const LIKE_QUESTION_SUCCESS = 'LIKE_QUESTION_SUCCESS';
export const DISLIKE_QUESTION_SUCCESS = 'DISLIKE_QUESTION_SUCCESS';