export const CREATE_ISSUE_ERROR = 'CREATE_ISSUE_ERROR';
export const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';

export const SELECT_ISSUE = 'SELECT_ISSUE';
export const SELECT_ISSUE_SUCCESS = 'SELECT_ISSUE_SUCCESS';
export const SELECT_ISSUE_ERROR = 'SELECT_ISSUE_ERROR';

export const DELETE_ISSUE_ERROR = 'DELETE_ISSUE_ERROR';
export const DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE_SUCCESS';

export const UNDELETE_ISSUE_ERROR = 'UNDELETE_ISSUE_ERROR';

export const UPDATE_ISSUE_ERROR = 'UPDATE_ISSUE_ERROR';
export const UPDATE_ISSUE_SUCCESS = 'UPDATE_ISSUE_SUCCESS';

export const FILTER_ISSUES = 'FILTER_ISSUES';
export const FILTER_ISSUE_SELECTED = 'FILTER_ISSUE_SELECTED';
export const LOAD_ISSUES_SUCCESS = 'LOAD_ISSUES_SUCCESS';
export const UNLOAD_ISSUES_SUCCESS = 'UNLOAD_ISSUES_SUCCESS';
