export const CREATE_ISSUE_ERROR = 'CREATE_ISSUE_ERROR';
export const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';

export const CREATE_ISSUE_ANSWER = 'CREATE_ISSUE_ANSWER';
export const CREATE_ISSUE_ANSWER_ERROR = 'CREATE_ISSUE_ANSWER_ERROR';
export const CREATE_ISSUE_ANSWER_SUCCESS = 'CREATE_ISSUE_ANSWER_SUCCESS';

export const DELETE_ISSUE_ERROR = 'DELETE_ISSUE_ERROR';
export const DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE_SUCCESS';

export const UPDATE_ISSUE_ERROR = 'UPDATE_ISSUE_ERROR';
export const UPDATE_ISSUE_SUCCESS = 'UPDATE_ISSUE_SUCCESS';

export const FILTER_ISSUES = 'FILTER_ISSUES';
export const FILTER_ISSUE_SELECTED = 'FILTER_ISSUE_SELECTED';

export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const GET_MOST_RECOMMENDED_APP_ICON_SUCCESS = 'GET_MOST_RECOMMENDED_APP_ICON_SUCCESS';

export const LOAD_ISSUES_SUCCESS = 'LOAD_ISSUES_SUCCESS';
export const UNLOAD_ISSUES_SUCCESS = 'UNLOAD_ISSUES_SUCCESS';

export const FETCH_LIKES_QUANTITY_QUESTION_SUCCESS = 'FETCH_LIKES_QUANTITY_QUESTION_SUCCESS';
