export const LOAD_LIKES_ISSUE = 'LOAD_LIKES_ISSUE';
export const LOAD_LIKES_ANSWER_SUCCESS = 'LOAD_LIKES_ANSWER_SUCCESS';
export const LOAD_LIKES_ANSWER = 'LOAD_LIKES_ANSWER';

export const LIKE_ISSUE = 'LIKE_ISSUE';
export const LIKE_ANSWER = 'LIKE_ANSWER';

export const CREATE_LIKES_ANSWER_SUCCESS = 'CREATE_LIKES_ANSWER_SUCCESS';
export const UPDATE_LIKES_ANSWER_SUCCESS = 'UPDATE_LIKES_ANSWER_SUCCESS';
export const DELETE_LIKES_ANSWER_SUCCESS = 'DELETE_LIKES_ANSWER_SUCCESS';